version: "3.4"

services:
  postgres:
    image: postgres
    restart: always
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PGPORT: ${DB_PORT}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
    volumes:
      - /docker-volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
