# Authentication service

### Login
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "password"
}

### Registration
POST http://localhost:3001/api/auth/registration
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "asd"
}

### Verify token
POST http://localhost:3001/api/token/verify
Content-Type: application/json

{
  "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg4NDM5OTg4LCJleHAiOjE1ODg1MjYzODh9.4DGPBuHmTIBZJ_-gb8a8r0pfGewS6bBewNshNCRRY7Q"
}

### Get user by id
GET http://localhost:3001/api/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg4NDM5OTg4LCJleHAiOjE1ODg1MjYzODh9.4DGPBuHmTIBZJ_-gb8a8r0pfGewS6bBewNshNCRRY7Q

### Update user
PUT http://localhost:3001/api/user/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg4NDM5OTg4LCJleHAiOjE1ODg1MjYzODh9.4DGPBuHmTIBZJ_-gb8a8r0pfGewS6bBewNshNCRRY7Q

{
  "email": "email@gmail.com",
  "age": 12
}
